abstract: bind to foreign libraries in three seconds flat
author: 'Anatoly Vorobey, C<< <avorobey@pobox.com> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: MIT
name: Superglue
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
version: 0.01
